name: track_star
description: A new Flutter project.
publish_to: 'none'
version: 1.1.0+3

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  date_time_picker: ^2.1.0
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  cloud_firestore: ^3.1.10
  provider: ^6.0.2
  intl: ^0.17.0
  table_calendar: ^3.0.5
  json_annotation: ^4.4.0
  uuid: ^3.0.6
  page_view_indicators: ^2.0.0
  grouped_list: ^4.2.0
  flutter_launcher_icons: ^0.9.2
  firebase_analytics: ^9.1.7
  home_widget: ^0.1.5
  url_launcher: ^6.1.1
  package_info_plus: ^1.4.2

dev_dependencies:
  json_serializable: ^6.1.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.8

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/