// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC3MYfS6SLR3Gs-pSwcf9URN0NPEfa4gA',
    appId: '1:475218778877:android:ec4db7444240e485d23c94',
    messagingSenderId: '475218778877',
    projectId: 'trackstar-f0071',
    storageBucket: 'trackstar-f0071.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFo_fDvmrl0j9yxm_32TeUtdbWSyz0Ek8',
    appId: '1:475218778877:ios:b8a31975054b2900d23c94',
    messagingSenderId: '475218778877',
    projectId: 'trackstar-f0071',
    storageBucket: 'trackstar-f0071.appspot.com',
    iosClientId: '475218778877-3qjaitmdjkdhdol2kedaiq2oj2mls732.apps.googleusercontent.com',
    iosBundleId: 'com.trackstar.app',
  );
}
