// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTMCDkW8bPTc2qvko9oZ7cmPvSoMgcCHM',
    appId: '1:615688507283:android:71ad9baa1996bb8248e266',
    messagingSenderId: '615688507283',
    projectId: 'trackstar-dev',
    storageBucket: 'trackstar-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKScRo2QrzUrmVRRsTOAf3hDQxXUP8f8M',
    appId: '1:615688507283:ios:ecad16b3ef0c6a1548e266',
    messagingSenderId: '615688507283',
    projectId: 'trackstar-dev',
    storageBucket: 'trackstar-dev.appspot.com',
    iosClientId: '615688507283-bj40652u50n6a2q6ji424pq0navan6nq.apps.googleusercontent.com',
    iosBundleId: 'com.mveritym.track-star',
  );
}
